export default {
	colors: {
		primary: '#1F2937',
		secondary: '#F0BC74',
		tertiary: '#31316A',
		danger: '#E11D48',
		info: '#2361CE',
		warning: '#FBA918',
		success: '#10B981',
		dark: '#111827',
		gray: '#374151',
		light: '#1F2937',
		white: '#fff',
	},
	h1: {
		fontWeight: 'bold',
		marginTop: 10,
		fontSize: 20,
		color: '#1F2937',
	},
	container: {
		flex: 1,
		alignItems: 'center',
		justifyContent: 'center',
		backgroundColor: '#F2F4F6',
	},
	inputContainer: {
		flex: 1,
		marginTop: 30,
		width: '90%',
		padding: 20,
		borderRadius: 10,
		backgroundColor: '#fff',
		alignItems: 'stretch',
	},
	backgroundColor: '#F2F4F6',
	CheckBox: {
		containerStyle: {
			backgroundColor: 'transparent',
			borderColor: 'transparent',
			marginLeft: 0,
		},
	},
	Button: {
		marginTop: 10,
		orderRadius: 10,
		alignItems: 'center',
		justifyContent: 'center',
		elevation: 10,
		shadowOpacity: 20,
		shadowColor: '#ccc',
		titleStyle: {
			fontWeight: 'bold',
			color: '#fff',
		},
	},
};
