const ENUM_ACTION_TYPE = Object.freeze({
	ALERT_EMAIL: 'ALERT_EMAIL',
	ALERT_SMS: 'ALERT_SMS',
	ALERT_TELEGRAM: 'ALERT_TELEGRAM',
	ORDER: 'ORDER',
	TRAILING: 'TRAILING',
	WITHDRAW: 'WITHDRAW',
});

export { ENUM_ACTION_TYPE };
