const ORDER_STATUS = Object.freeze({
	CANCELED: 'CANCELED',
	EXPIRED: 'EXPIRED',
	FILLED: 'FILLED',
	NEW: 'NEW',
	PARTIALLY_FILLED: 'PARTIALLY_FILLED',
	REJECTED: 'REJECTED',
});

const ORDER_SIDE = Object.freeze({
	BUY: 'BUY',
	SELL: 'SELL',
});

const ORDER_TYPE = Object.freeze({
	LIMIT: 'LIMIT',
	MARKET: 'MARKET',
	STOP_LOSS_LIMIT: 'STOP_LOSS_LIMIT',
	TAKE_PROFIT_LIMIT: 'TAKE_PROFIT_LIMIT',
	TRAILING_STOP: 'TRAILING_STOP',
});

export { ORDER_STATUS, ORDER_SIDE, ORDER_TYPE };
